name: Release package
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13'
    - name: install dependences
      run: |
        go get -u go.zoe.im/gopkg
        echo $GOPATH
        whereis gopkg
      env:
        GOPATH: /tmp/go
    - name: generate static content
      run: /tmp/go/bin/gopkg gen -o . -d
    - name: public content to github
      run: |
        echo Publish to github
        git checkout master
        git add -f --ignore-errors --all
        git -c user.name='Zoe' -c user.email='hi@zoe.im' commit -m ":tada: release pacakge"
        git push -f -q https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
