name: Release package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13'
    - name: install dependences
      run: |
        go get -u go.zoe.im/gopkg
        echo $GOPATH
        whereis gopkg
      env:
        GOPATH: /tmp/go
    - name: generate static conten
      run: /tmp/go/bin/gopkg gen -o . -d
    - name: public content to github
      run: |
        echo Publish to github
        git add -f --ignore-errors --all
        git -c user.name='Zoe' -c user.email='hi@zoe.im' commit -m ":tada: release pacakge"
        ls -al
        git push -f -q https://$GH_USER:$GH_TOKEN@github.com/$BUILD_REPOSITORY_ID $TARGET_BRANCH
