name: Release package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: release package
      run: |
        echo Relase package.
        echo Install gopkg.
        go get -u go.zoe.im/gopkg
        echo Generate files.
        gopkg gen -o . -d
        echo Publish to github
        git add -f --ignore-errors --all
        git -c user.name='Zoe' -c user.email='hi@zoe.im' commit -m ":tada: release pacakge"
        ls -al
        # git push -f -q https://$GH_USER:$GH_TOKEN@github.com/$BUILD_REPOSITORY_ID $TARGET_BRANCH
